import chestImage from "../assets/images/chest.jpg"
import backImage from "../assets/images/back.jpg"
import shouldersImage from '../assets/images/shoulders.jpg'
import cardioImage from '../assets/images/cardio.jpg'
import quadsImage from '../assets/images/quads.jpg'
import tricepsImage from '../assets/images/triceps.jpg'
import glutesImage from '../assets/images/glutes.jpg'
import calvesImage from "../assets/images/calves.jpg"
import hamstringImage from '../assets/images/hamstring.jpg'
import coreImage from '../assets/images/abs.jpg'
import bicepsImage from '../assets/images/biceps.jpg'

export const allExercises = [
    {
        name: 'flat dumbbell bench press',
        id: 1,
        equipment: 'dumbbells',
        bodyPart: 'chest',
        imageUrl: chestImage,
        videoUrl: "https://www.youtube.com/watch?v=VmB1G1K7v94",
        secondaryTarget: ['front-delts','triceps'],

    },
    {
        name: 'barbell back squat',
        id: 2,
        equipment: 'barbell',
        bodyPart: 'quads',
        imageUrl: quadsImage,
        videoUrl: "https://www.youtube.com/watch?v=VZ90qWlfQUE",
        secondaryTarget: ['glutes', 'lower-back'],
    },
    
    { 
        name: 'bicep curls',
        id: 22,
        equipment: 'dumbbells',
        bodyPart: 'biceps',
        imageUrl: bicepsImage,
        videoUrl: "https://www.youtube.com/watch?v=XE_pHwbst04",
        secondaryTarget: ['forearms'],
    },
    { 
        name: 'preacher curls',
        id: 23,
        equipment: 'ez curl bar',
        bodyPart: 'biceps',
        imageUrl: bicepsImage,
        videoUrl: "https://www.youtube.com/watch?v=Gydpcouclx8",
        secondaryTarget: ['brachialis'],
    },
    { 
        name: 'overhead tricep extension',
        id: 24,
        equipment: 'dumbbells',
        bodyPart: 'triceps',
        imageUrl: tricepsImage,
        videoUrl: "https://www.youtube.com/watch?v=-Vyt2QdsR7E",
        secondaryTarget: ['shoulders'],
    },
    { 
        name: 'cable lateral raises',
        id: 26,
        equipment: 'cable',
        bodyPart: 'shoulders',
        imageUrl: shouldersImage,
        videoUrl: "https://www.youtube.com/watch?v=Z5FA9aq3L6A",
        secondaryTarget: ['traps'],
    },
    { 
        name: 'standing calf raises',
        id: 27,
        equipment: 'bodyweight',
        bodyPart: 'calves',
        imageUrl: calvesImage,
        videoUrl: "https://www.youtube.com/watch?v=eMTy3qylqnE",
        secondaryTarget: ['soleus'],
    },
    { 
        name: 'seated narrow-grip cable rows',
        id: 28,
        equipment: 'cable',
        bodyPart: 'back',
        imageUrl: backImage,
        videoUrl: "https://www.youtube.com/watch?v=vwHG9Jfu4sw",
        secondaryTarget: ['middle-back', 'biceps'],
    },
    { 
        name: 'incline dumbbell press',
        id: 29,
        equipment: 'dumbbells',
        bodyPart: 'chest',
        imageUrl: chestImage,
        videoUrl: "https://www.youtube.com/watch?v=IP4oeKh1Sd4&list=PLQCT4v41-dIi9aVDMedFkPyjusfsd5dMU&index=8",
        secondaryTarget: ['front delts', 'triceps'],
    },
    { 
        name: 'barbell front squats',
        id: 30,
        equipment: 'barbell',
        bodyPart: 'quads',
        imageUrl: quadsImage,
        videoUrl: "https://www.youtube.com/watch?v=I5GaxSYLCSc",
        secondaryTarget: ['glutes', 'core'],
    },
    
    { 
        name: 'mountain climbers',
        id: 32,
        equipment: 'bodyweight',
        bodyPart: 'core',
        imageUrl: coreImage,
        videoUrl: "https://www.youtube.com/watch?v=cnyTQDSE884",
        secondaryTarget: ['hip flexors', 'shoulders'],
    },
    { 
        name: 'dumbbell chest fly',
        id: 33,
        equipment: 'dumbbells',
        bodyPart: 'chest',
        imageUrl: chestImage,
        videoUrl: "https://www.youtube.com/watch?v=eozdVDA78K0",
        secondaryTarget: ['front delts'],
    },
    { 
        name: 'face pulls',
        id: 34,
        equipment: 'cable',
        bodyPart: 'shoulders',
        imageUrl: shouldersImage,
        videoUrl: "https://www.youtube.com/watch?v=eFxMixk_qPQ",
        secondaryTarget: ['traps', 'biceps'],
    },
    { 
        name: 'good mornings',
        id: 35,
        equipment: 'barbell',
        bodyPart: 'back',
        imageUrl: backImage,
        videoUrl: "https://www.youtube.com/watch?v=VkNcc0BQrpA",
        secondaryTarget: ['glutes', 'hamstrings'],
    },
    { 
        name: 'deadlifts',
        id: 36,
        equipment: 'barbell',
        bodyPart: 'back',
        imageUrl: backImage,
        videoUrl: "https://www.youtube.com/watch?v=r4MzxtBKyNE",
        secondaryTarget: ['hamstrings', 'glutes'],
    },
    
    { 
        name: 'barbell hip thrusts',
        id: 38,
        equipment: 'barbell',
        bodyPart: 'glutes',
        imageUrl: glutesImage,
        videoUrl: "https://www.youtube.com/watch?v=Zp26q4BY5HE",
        secondaryTarget: ['hamstrings', 'core'],
    },
    
    { 
        name: 'high knees',
        id: 40,
        equipment: 'bodyweight',
        bodyPart: 'cardio',
        imageUrl: cardioImage,
        videoUrl: "https://www.youtube.com/watch?v=ZNDHivUg7vA",
        secondaryTarget: ['quads', 'calves'],
    },
    { 
        name: 'box jumps',
        id: 41,
        equipment: 'box',
        bodyPart: 'quads',
        imageUrl: quadsImage,
        videoUrl: "https://www.youtube.com/watch?v=NBY9-kTuHEk",
        secondaryTarget: ['glutes', 'hamstrings'],
    },
    { 
        name: 'kettlebell swings',
        id: 42,
        equipment: 'kettlebell',
        bodyPart: 'cardio',
        imageUrl: cardioImage,
        videoUrl: "https://www.youtube.com/watch?v=cY38L70lxro",
        secondaryTarget: ['glutes', 'hamstrings', "cardio"],
    },
    { 
        name: 'medicine ball slams',
        id: 43,
        equipment: 'medicine ball',
        bodyPart: 'core',
        imageUrl: coreImage,
        videoUrl: "https://www.youtube.com/watch?v=6vXHh-Lhb2o",
        secondaryTarget: ['shoulders', 'triceps', "cardio"],
    },
    { 
        name: 'dumbbell step-ups',
        id: 44,
        equipment: 'dumbbells',
        bodyPart: 'quads',
        imageUrl: quadsImage,
        videoUrl: "https://www.youtube.com/watch?v=9ZknEYboBOQ",
        secondaryTarget: ['glutes', 'calves'],
    },
    { 
        name: 'jump squats',
        id: 45,
        equipment: 'bodyweight',
        bodyPart: 'quads',
        imageUrl: quadsImage,
        videoUrl: "https://www.youtube.com/watch?v=5xv0DKqe5XQ",
        secondaryTarget: ['glutes', 'calves'],
    },
    { 
        name: 'landmine press',
        id: 46,
        equipment: 'barbell',
        bodyPart: 'shoulders',
        imageUrl: shouldersImage,
        videoUrl: "https://www.youtube.com/watch?v=t9GuiNQo1O4",
        secondaryTarget: ['triceps', 'chest'],
    },
    { 
        name: 'side planks',
        id: 47,
        equipment: 'bodyweight',
        bodyPart: 'core',
        imageUrl: coreImage,
        videoUrl: "https://www.youtube.com/watch?v=N_s9em1xTqU",
        secondaryTarget: ['obliques', 'shoulders'],
    },
    { 
        name: 'close-grip bench press',
        id: 48,
        equipment: 'barbell',
        bodyPart: 'triceps',
        imageUrl: tricepsImage,
        videoUrl: "https://www.youtube.com/watch?v=wxVRe9pmJdk",
        secondaryTarget: ['chest', 'front delts'],
    },
    { 
        name: 'incline push-ups',
        id: 49,
        equipment: 'bodyweight',
        bodyPart: 'chest',
        imageUrl: chestImage,
        videoUrl: "https://www.youtube.com/watch?v=Me9bHFAxnCs",
        secondaryTarget: ['triceps', 'front delts'],
    },
    { 
        name: 'decline push-ups',
        id: 50,
        equipment: 'bodyweight',
        bodyPart: 'chest',
        imageUrl: chestImage,
        videoUrl: "https://www.youtube.com/watch?v=5QFjmotLfW4",
        secondaryTarget: ['front delts', 'triceps'],
    },
    {
        name: 'flat barbell bench press',
        id: 51,
        equipment: 'barbell',
        bodyPart: 'chest',
        imageUrl: chestImage,
        videoUrl: "https://www.youtube.com/watch?v=lWFknlOTbyM&list=PLQCT4v41-dIi9aVDMedFkPyjusfsd5dMU&index=13",
        secondaryTarget: ['front delts', 'triceps'],
    },
    {
        name: 'incline barbell bench press',
        id: 52,
        equipment: 'barbell',
        bodyPart: 'chest',
        imageUrl: chestImage,
        videoUrl: "https://www.youtube.com/watch?v=11gY7Q5D5wo",
        secondaryTarget: ['front delts', 'triceps'],
    },
    {
        name: 'incline dumbbell bench press',
        id: 53,
        equipment: 'dumbbell',
        bodyPart: 'chest',
        imageUrl: chestImage,
        videoUrl: "https://www.youtube.com/watch?v=IP4oeKh1Sd4",
        secondaryTarget: ['front delts', 'triceps'],
    },
    
    {
        name: 'pull-up',
        id: 3,
        equipment: 'bodyweight',
        bodyPart: 'back',
        imageUrl: backImage,
        videoUrl: "https://www.youtube.com/watch?v=eGo4IYlbE5g",
        secondaryTarget: ['biceps', 'rear-delts'],
    },
    {
        name: 'push-up',
        id: 4,
        equipment: 'bodyweight',
        bodyPart: 'chest',
        imageUrl: chestImage,
        videoUrl: "https://www.youtube.com/watch?v=F0mFvxZelaE",
        secondaryTarget: ['triceps', 'front-delts'],
    },
    {
        name: 'single arm dumbbell row',
        id: 5,
        equipment: 'dumbbell',
        bodyPart: 'back',
        imageUrl: backImage,
        videoUrl: "https://www.youtube.com/watch?v=dFzUjzfih7k",
        secondaryTarget: ['traps', 'rear-delts','rhomboids'],
    },
    {
        name: 'incline bicep curl',
        id: 6,
        equipment: 'dumbbells',
        bodyPart: 'biceps',
        imageUrl: bicepsImage,
        videoUrl: "https://www.youtube.com/watch?v=HhHHBj3qTJ4&list=PLQCT4v41-dIi9aVDMedFkPyjusfsd5dMU&index=12",
        secondaryTarget: [],
    },
    {
        name: 'tricep dips',
        id: 7,
        equipment: 'bodyweight',
        bodyPart: 'triceps',
        imageUrl: tricepsImage,
        videoUrl: "https://www.youtube.com/watch?v=TrJVszDm7ik&list=PLQCT4v41-dIi9aVDMedFkPyjusfsd5dMU&index=10",
        secondaryTarget: ['chest', 'front-delts'],
    },
    {
        name: 'plank',
        id: 8,
        equipment: 'bodyweight',
        bodyPart: 'core',
        imageUrl: coreImage,
        videoUrl: "https://www.youtube.com/watch?v=pvIjsG5Svck",
        secondaryTarget: ['lower-back', 'shoulders'],
    },
    {
        name: 'lunges',
        id: 9,
        equipment: 'bodyweight',
        bodyPart: 'quads',
        imageUrl: quadsImage,
        videoUrl: "https://www.youtube.com/watch?v=tTej-ax9XiA",
        secondaryTarget: ['glutes', 'quads'],
    },
    {
        name: 'dumbbell overhead shoulder press',
        id: 10,
        equipment: 'dumbbells',
        bodyPart: 'shoulders',
        imageUrl: shouldersImage,
        videoUrl: "https://www.youtube.com/watch?v=rO_iEImwHyo&list=PLQCT4v41-dIi9aVDMedFkPyjusfsd5dMU&index=9",
        secondaryTarget: ['triceps', 'upper-chest'],
    },
    {
        name: 'lat pulldown',
        id: 11,
        equipment: 'machine',
        bodyPart: 'back',
        imageUrl: backImage,
        videoUrl: "https://www.youtube.com/watch?v=43hWj8mfYGY&list=PLQCT4v41-dIi9aVDMedFkPyjusfsd5dMU&index=14",
        secondaryTarget: ['biceps', 'rear-delts'],
    },
    {
        name: 'leg press',
        id: 12,
        equipment: 'machine',
        bodyPart: 'quads',
        imageUrl: quadsImage,
        videoUrl: "https://www.youtube.com/watch?v=VFk3RzndUEc",
        secondaryTarget: ['glutes', 'hamstrings'],
    },
    {
        name: 'cable chest fly',
        id: 13,
        equipment: 'cable',
        bodyPart: 'chest',
        imageUrl: chestImage,
        videoUrl: "https://www.youtube.com/watch?v=PRw7ieDBLl4",
        secondaryTarget: [],
    },
    {
        name: 'dumbbell lateral raises',
        id: 14,
        equipment: 'dumbbells',
        bodyPart: 'shoulders',
        imageUrl: shouldersImage,
        videoUrl: "https://www.youtube.com/watch?v=PzsMitRdI_8",
        secondaryTarget: ['traps'],
    },
    {
        name: 'sit-up',
        id: 15,
        equipment: 'bodyweight',
        bodyPart: 'core',
        imageUrl: coreImage,
        videoUrl: "https://www.youtube.com/watch?v=UMaZGY6CbC4",
        secondaryTarget: ['hip-flexors'],
    },
    {
        name: 'romanian deadlift',
        id: 16,
        equipment: 'barbell',
        bodyPart: 'hamstrings',
        imageUrl: hamstringImage,
        videoUrl: "https://www.youtube.com/watch?v=3VXmecChYYM&list=PLQCT4v41-dIi9aVDMedFkPyjusfsd5dMU&index=5",
        secondaryTarget: ['glutes', 'lower-back'],
    },
    {
        name: 'seated calf raise',
        id: 17,
        equipment: 'machine',
        bodyPart: 'calves',
        imageUrl: calvesImage,
        videoUrl: "https://www.youtube.com/watch?v=6O5hh1rBtx8",
        secondaryTarget: [],
    },
    {
        name: 'seated wide-grip row',
        id: 18,
        equipment: 'cable',
        bodyPart: 'back',
        imageUrl: backImage,
        videoUrl: "https://www.youtube.com/watch?v=sjJ0z4R3w0M",
        secondaryTarget: ['biceps', 'rear-delts'],
    },
    {
        name: 'hammer curl',
        id: 19,
        equipment: 'dumbbells',
        bodyPart: 'biceps',
        imageUrl: bicepsImage,
        videoUrl: "https://www.youtube.com/watch?v=BRVDS6HVR9Q",
        secondaryTarget: [],
    },
    {
        name: 'Russian twist',
        id: 20,
        equipment: 'bodyweight',
        bodyPart: 'core',
        imageUrl: coreImage,
        videoUrl: "https://www.youtube.com/watch?v=wkD8rjkodUI",
        secondaryTarget: ['obliques'],
    },
    { 
        name: 'glute bridges',
        id: 31,
        equipment: 'bodyweight',
        bodyPart: 'glutes',
        imageUrl: glutesImage,
        videoUrl: "https://www.youtube.com/watch?v=OUgsJ8-Vi0E",
        secondaryTarget: ['hamstrings', 'lower back'],
    },
    { 
        name: 'jumping jacks',
        id: 37,
        equipment: 'bodyweight',
        bodyPart: 'cardio',
        imageUrl: cardioImage,
        videoUrl: "https://www.youtube.com/watch?v=iSSAk4XCsRA",
        secondaryTarget: ['shoulders', 'calves'],
    },
    { 
        name: 'burpees',
        id: 39,
        equipment: 'bodyweight',
        bodyPart: 'cardio',
        imageUrl: cardioImage,
        videoUrl: "https://www.youtube.com/watch?v=G2hv_NYhM-A",
        secondaryTarget: ['arms', 'chest','legs'],
    },
    { 
        name: 'treadmill',
        id: 54,
        equipment: 'treadmill',
        bodyPart: 'cardio',
        imageUrl: cardioImage,
        videoUrl: "https://www.youtube.com/watch?v=HBPMvFkpNgE",
        secondaryTarget: ['quads', 'hamstrings', 'calves'],
    },
    { 
        name: 'cable crunch',
        id: 25,
        equipment: 'cable machine',
        bodyPart: 'core',
        imageUrl: coreImage, 
        videoUrl: "https://www.youtube.com/watch?v=3qjoXDTuyOE",
        secondaryTarget: ['obliques', 'upper abs'],
    },
    
    { 
        name: 'hanging knee raise',
        id: 21,
        equipment: 'pull-up bar',
        bodyPart: 'core',
        imageUrl: coreImage, 
        videoUrl: "https://www.youtube.com/watch?v=iC_fu-XjNPo",
        secondaryTarget: ['lower abs', 'hip flexors','forearms'],
    },
    
    { 
        name: 'toes to bar',
        id: 55,
        equipment: 'pull-up bar',
        bodyPart: 'core',
        imageUrl: coreImage, 
        videoUrl: "https://www.youtube.com/watch?v=qcosxmOBQK0",
        secondaryTarget: ['lower abs', 'lats'],
    },
    {
        name: 'seated leg curl',
        id: 56,
        equipment: 'machine',
        bodyPart: 'hamstrings',
        imageUrl: hamstringImage,
        videoUrl: "https://www.youtube.com/watch?v=t9sTSr-JYSs",
        secondaryTarget: ['calves'],
    },
    {
        name: 'single-leg deadlift',
        id: 57,
        equipment: 'bodyweight',
        bodyPart: 'hamstrings',
        imageUrl: hamstringImage,
        videoUrl: "https://www.youtube.com/watch?v=FAFYkQCQJYo",
        secondaryTarget: ['glutes', 'core','hips'],
    },
    
    {
        name: "archer push-up",
        id: 58,
        equipment: "bodyweight",
        bodyPart: "chest",
        imageUrl: chestImage,
        videoUrl: "https://www.youtube.com/watch?v=jiA3RnMxFU0",
        secondaryTarget: ["shoulders", "triceps"]
    },
    {
        name: "cossack squat",
        id: 59,
        equipment: "bodyweight",
        bodyPart: "quads",
        imageUrl: quadsImage,
        videoUrl: "https://www.youtube.com/watch?v=p_scPPvWD2I",
        secondaryTarget: ["hips", "glutes"]
    },
    {
        name: "spiderman push-up",
        id: 60,
        equipment: "bodyweight",
        bodyPart: "chest",
        imageUrl: chestImage,
        videoUrl: "https://www.youtube.com/watch?v=qG2oWGqXSdw",
        secondaryTarget: ["core", "triceps","ahoulders"]
    },
    {
        name: "pistol squat",
        id: 61,
        equipment: "bodyweight",
        bodyPart: "quads",
        imageUrl: quadsImage,
        videoUrl: "https://www.youtube.com/watch?v=TVGdDwp02sw",
        secondaryTarget: ["glutes", "hips"]
    },
    {
        name: "wall sit",
        id: 62,
        equipment: "bodyweight",
        bodyPart: "quads",
        imageUrl: quadsImage,
        videoUrl: "https://www.youtube.com/watch?v=cWTZ8Am1Ee0",
        secondaryTarget: ["hamstrings", "glutes"]
    },
    {
        name: "L-sit hold",
        id: 63,
        equipment: "bodyweight",
        bodyPart: "core",
        imageUrl: coreImage,
        videoUrl: "https://www.youtube.com/watch?v=RkLUSpe1Ilk",
        secondaryTarget: ["hip flexors", "triceps"]
    },
    {
        name: "frogger jump",
        id: 64,
        equipment: "bodyweight",
        bodyPart: "quads",
        imageUrl: quadsImage,
        videoUrl: "https://www.youtube.com/watch?v=Brkz-7w8gsY",
        secondaryTarget: ["fullbody", "glutes", "core"]
    },
    {
        name: "bear crawl",
        id: 65,
        equipment: "bodyweight",
        bodyPart: "shoulders",
        imageUrl: shouldersImage,
        videoUrl: "https://www.youtube.com/watch?v=Ee1BQNI6zN4",
        secondaryTarget: ["core", "hips"]
    },
    {
        name: "shrimp squat",
        id: 66,
        equipment: "bodyweight",
        bodyPart: "quads",
        imageUrl: quadsImage,
        videoUrl: "https://www.youtube.com/watch?v=xfl7SDj0Gzs",
        secondaryTarget: ["glutes", "hamstrings"]
    },
    {
        name: "dragon flag",
        id: 67,
        equipment: "bodyweight",
        bodyPart: "core",
        imageUrl: coreImage,
        videoUrl: "https://www.youtube.com/watch?v=U5pviWt7sMo",
        secondaryTarget: ["shoulders", "hip flexors"]
    },
    
    {
        name: "dumbbell thruster",
        id: 68,
        equipment: "dumbbells",
        bodyPart: "shoulders",
        imageUrl: shouldersImage,
        videoUrl: "https://www.youtube.com/watch?v=-rHJkjHUbmo",
        secondaryTarget: ["quads", "triceps"]
    },
    {
        name: "renegade row",
        id: 69,
        equipment: "dumbbells",
        bodyPart: "back",
        imageUrl: backImage,
        videoUrl: "https://www.youtube.com/watch?v=OlpPaGyywyY",
        secondaryTarget: ["core", "shoulders"]
    },
    {
        name: "dumbbell pullover",
        id: 70,
        equipment: "dumbbells",
        bodyPart: "back",
        imageUrl: backImage,
        videoUrl: "https://www.youtube.com/watch?v=FK4rHfWKEac",
        secondaryTarget: ["chest", "core"]
    },
    {
        name: "dumbbell split squat",
        id: 71,
        equipment: "dumbbells",
        bodyPart: "quads",
        imageUrl: quadsImage,
        videoUrl: "https://www.youtube.com/watch?v=MEG6blZtUpc",
        secondaryTarget: ["glutes", "hamstrings"]
    },
    {
        name: "dumbbell woodchop",
        id: 72,
        equipment: "dumbbells",
        bodyPart: "core",
        imageUrl: coreImage,
        videoUrl: "https://www.youtube.com/watch?v=Rf-2l8Z40dg",
        secondaryTarget: ["shoulders", "obliques"]
    },
    {
        name: "dumbbell clean and press",
        id: 73,
        equipment: "dumbbells",
        bodyPart: "shoulders",
        imageUrl: shouldersImage,
        videoUrl: "https://www.youtube.com/watch?v=sZ4XMWn8bAU",
        secondaryTarget: ["back", "quads", "core","fullbody"]
    },
    {
        name: "dumbbell reverse fly",
        id: 74,
        equipment: "dumbbells",
        bodyPart: "back",
        imageUrl: backImage,
        videoUrl: "https://www.youtube.com/watch?v=JoCRRZ3zRtI",
        secondaryTarget: ["rear-delts"]
    },
    {
        name: "dumbbell Bulgarian split squat",
        id: 75,
        equipment: "dumbbells",
        bodyPart: "quads",
        imageUrl: quadsImage,
        videoUrl: "https://www.youtube.com/watch?v=SkNsa3eBwLA",
        secondaryTarget: ["glutes", "hamstrings"]
    },
    
    {
        name: "barbell snatch",
        id: 76,
        equipment: "barbell",
        bodyPart: "shoulders",
        imageUrl: shouldersImage,
        videoUrl: "https://www.youtube.com/watch?v=eZvy51ucmOc",
        secondaryTarget: ["fullbody", "legs", "core"]
    },
    {
        name: "barbell reverse grip bench press",
        id: 77,
        equipment: "barbell",
        bodyPart: "chest",
        imageUrl: chestImage,
        videoUrl: "https://www.youtube.com/watch?v=_y5VJGlk32I",
        secondaryTarget: ["shoulders", "triceps"]
    },
    {
        name: "barbell bent-over row",
        id: 78,
        equipment: "barbell",
        bodyPart: "back",
        imageUrl: backImage,
        videoUrl: "https://www.youtube.com/watch?v=FWJR5Ve8bnQ",
        secondaryTarget: ["biceps", "rear delts"]
    },
    {
        name: "cable concentration curl",
        id: 79,
        equipment: "cable",
        bodyPart: "biceps",
        imageUrl: bicepsImage,
        videoUrl: "https://www.youtube.com/watch?v=fDYD9_SuJjw",
        secondaryTarget: ["brachialis"]
    },
    {
        name: "cable reverse curl",
        id: 80,
        equipment: "cable",
        bodyPart: "biceps",
        imageUrl: bicepsImage,
        videoUrl: "https://www.youtube.com/watch?v=23-WiuDnsZ0",
        secondaryTarget: ["brachialis, forearm"]
    },
    {
        name: "cable woodchop",
        id: 81,
        equipment: "cable",
        bodyPart: "core",
        imageUrl: coreImage,
        videoUrl: "https://www.youtube.com/watch?v=ZDt4MCvjMAA",
        secondaryTarget: ["obliques", "shoulders"]
    },
    {
        name: "machine glute kickback",
        id: 82,
        equipment: "cable",
        bodyPart: "glutes",
        imageUrl: glutesImage,
        videoUrl: "https://www.youtube.com/watch?v=8UzzL5thzRg",
        secondaryTarget: ["hamstrings","core"]
    },
    {
        name: "machine chest press",
        id: 83,
        equipment: "machine",
        bodyPart: "chest",
        imageUrl: chestImage,
        videoUrl: "https://www.youtube.com/watch?v=sqNwDkUU_Ps",
        secondaryTarget: ["shoulders", "triceps"]
    },
    {
        name: "cable tricep pushdown",
        id: 84,
        equipment: "cable",
        bodyPart: "triceps",
        imageUrl: tricepsImage,
        videoUrl: "https://www.youtube.com/watch?v=2-LAMcpzODU",
        secondaryTarget: ["shoulders"]
    },
    {
        name: "military press",
        id: 85,
        equipment: "barbell",
        bodyPart: "shoulders",
        imageUrl: shouldersImage,
        videoUrl: "https://www.youtube.com/watch?v=KP1sYz2VICk",
        secondaryTarget: ["triceps","traps"]
    },
    {
        name: "skull crushers",
        id: 86,
        equipment: "ez curl bar",
        bodyPart: "triceps",
        imageUrl: tricepsImage,
        videoUrl: "https://www.youtube.com/watch?v=d_KZxkY_0cM",
        secondaryTarget: ["front-delts"]
    }
      
      
      
      
      
      
    
];   
